
# SRoll3 parameter file generated by /scratch/cnt0028/ias1717/SHARED/bware/wrk_sroll21/run_stim/run_srollstim_sroll2.pyc
# for smottet
# on OCCIGEN
# at Fri Oct 18 14:17:10 2019

# PARAMETERS

#BeginRing   = 240
#EndRing     = 26050
#import healpy as hp
#import numpy as np

def main():

  bolo=['857-1','857-2','857-3','857-4']

  params  =vars()

  return params
