#!/bin/bash
#PBS -q mpi_4
#PBS -l select=4:ncpus=28:mem=115g
#PBS -l walltime=24:00:00
#PBS -N Dmaptest
#PBS -o /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4/scatout.log

echo 'PATH INIT DONE'
source /usr/share/Modules/3.2.10/init/bash
module purge
module load impi/5.1.3.258
module load valgrind/3.12.0__gcc-6.3.0


cd /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4
#export MKL_DEBUG_CPU_TYPE=5
echo 'READY FOR RUN'
./ressources &> /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4/memusage_scat.log &
#valgrind --suppressions=python.supp --error-limit=no --track-origins=yes ./troll_cfosat allday_hh.py &> /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4/scat.log
mpirun -np 112 ./troll_cfosat allday_hh.py &> /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4/scat_allday_hh.log
echo 'End'

