#!/bin/bash
#PBS -q mpi_3
#PBS -l select=3:ncpus=28:mem=115g
#PBS -l walltime=12:00:00
#PBS -N Dmaptest
#PBS -o /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4/scatout.log

echo 'PATH INIT DONE'
source /usr/share/Modules/3.2.10/init/bash
module purge
module load impi/5.1.3.258

cd /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4

echo 'READY FOR RUN'
./ressources &> /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4/memusage.log &
mpirun -np 84 ./troll_cfosat unit_loop_azi_hh_1y_100ring_JM.py &> /home1/datahome/jmdeloui/DATAWORK/SRoll/sroll4/test.log
echo 'End'

