#!/bin/bash
#PBS -q mpi_10
#PBS -l select=10:ncpus=28:mem=115g
#PBS -l walltime=12:00:00
#PBS -N Dmaptest

cd /home1/datawork/jmdeloui/Troll/iaocea/source/SrollEx

module purge
source srollex_setenv.sh
cd sroll4
echo 'PATH INIT DONE'
module load impi/5.1.3.258
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home1/datahome/jmdeloui/conda-env/tfgpu/lib

echo 'READY FOR RUN'
mpirun -np 256 ./troll_857 sroll3_857_data.py &> /home1/datawork/jmdeloui/Troll/iaocea/source/SrollEx/sroll4/sroll3_857_data3.log
#mpirun -np 16 ./test
echo 'End'
