#############################################################
###	Auto generate PyParams template by fillParLoader.py 	###
#############################################################

def main():
	BeginRing = 	#mandatory parameter
	EndRing = 	#mandatory parameter
	CrossPol = []
	number_of_CrossPol = 	#mandatory parameter
	Calibration = []
	number_of_Calibration = 	#mandatory parameter
	seuilcond = 	#mandatory parameter
	NEP = []
	number_of_NEP = 	#mandatory parameter
	Monop = []
	number_of_Monop = 	#mandatory parameter
	bolomask = []
	number_of_bolomask = 	#mandatory parameter
	SEED = []
	number_of_SEED = 	#mandatory parameter
	FITANGLE = 	#mandatory parameter
	FITPOLEFF = 	#mandatory parameter
	OUT_NOPOL = []
	number_of_OUT_NOPOL = 	#mandatory parameter
	FSLCOEF = []
	number_of_FSLCOEF = 	#mandatory parameter
	D_NOPOL = 	#mandatory parameter
	SAVEINTMAP = 	#mandatory parameter
	CALCODUST = 	#mandatory parameter
	DOMAXVRAIE = 	#mandatory parameter
	DOGAINDIP = 	#mandatory parameter
	CUTRG = 	#mandatory parameter
	AVGR0 = 
	DODIPCAL = 	#mandatory parameter
	TESTPOL = 	#mandatory parameter
	RSTEP = 	#mandatory parameter
	GAINSTEP = 	#mandatory parameter
	Nside = 	#mandatory parameter
	XI2STOP = 	#mandatory parameter
	AVGCO = 	#mandatory parameter
	AVGDUST = 	#mandatory parameter
	NITT = 	#mandatory parameter
	NADU = 	#mandatory parameter
	NADUSTEP = 	#mandatory parameter
	REMDIP = 	#mandatory parameter
	in_template_map_I = 	#mandatory parameter
	in_template_map_Q = 	#mandatory parameter
	in_template_map_U = 	#mandatory parameter
	REFMAPI = 
	REFMAPQ = 
	REFMAPU = 
	REMHDIP = 
	TEMPLATEMAP = 
	Signal_noPS = []
	number_of_Signal_noPS = 
	invgi = []
	number_of_invgi = 
	fsl = []
	number_of_fsl = 
	Theo_noPS = []
	number_of_Theo_noPS = 
	ADU = []
	number_of_ADU = 
	Theo_CO = 
	Theo_13CO = 
	in_polar_fit_Q = 
	in_polar_fit_U = 
	Theo_FREEFREE = 
	Theo_Dust_I = 
	Theo_Dust_Q = 
	Theo_Dust_U = 
	Sim_Dust_Q = 
	Sim_Dust_U = 
	Ptg_noPS = []
	number_of_Ptg_noPS = 
	Hit_noPS = []
	number_of_Hit_noPS = 
	ALMMAP = []
	number_of_ALMMAP = 
	DipOrb_noPS = []
	number_of_DipOrb_noPS = 
	Badring = []
	number_of_Badring = 
	VarGain = []
	number_of_VarGain = 
	Mask = 
	MAP = []
	number_of_MAP = 
	Out_Offset = []
	number_of_Out_Offset = 
	Out_Offset_corr = []
	number_of_Out_Offset_corr = 
	Out_xi2 = []
	number_of_Out_xi2 = 
	Out_xi2_corr = []
	number_of_Out_xi2_corr = 
	verbose = 
	dmc_output_path = 
	dmc_error_path = 
	stim_paramfiles = []
	number_of_stim_paramfiles = 
	MAPRINGS = []
	number_of_MAPRINGS = 
	ADDDIP = 
	KCMBIN = 
	addHPR_name = []
	number_of_addHPR_name = 
	addHPR_factor = []
	number_of_addHPR_factor = 
	addHPR_watts = []
	number_of_addHPR_watts = 
	AVGCO143 = 
	AVGDUST100 = 
	saveCOV = 
	delta_psi = 

	params  =vars()
	return params