#############################################################
###	Auto generate PyParams template by fillParLoader.py 	###
#############################################################

def main():
	BeginRing = 	#mandatory parameter
	EndRing = 	#mandatory parameter
	CrossPol = []
	number_of_CrossPol = 	#mandatory parameter
	ADDPOL = 
	Calibration = []
	number_of_Calibration = 	#mandatory parameter
	seuilcond = 	#mandatory parameter
	NEP = []
	number_of_NEP = 	#mandatory parameter
	Monop = []
	number_of_Monop = 	#mandatory parameter
	bolomask = []
	number_of_bolomask = 	#mandatory parameter
	DOCNN = []
	number_of_DOCNN = 
	CNN_CORE = 
	SEED = []
	number_of_SEED = 	#mandatory parameter
	OUT_NOPOL = []
	number_of_OUT_NOPOL = 	#mandatory parameter
	SUB_HPRCOEF = []
	number_of_SUB_HPRCOEF = 	#mandatory parameter
	D_NOPOL = 	#mandatory parameter
	SAVEINTMAP = 	#mandatory parameter
	CALLCNN = 
	CNN_WEIGHTS = 
	CNN_ITT = 
	CNN_START = 
	CNN_LEARN_PARAM = 
	CNN_TMPID = 
	CNN_RESIDU = 
	CNN_XSIZE = 
	CNN_YSIZE = 
	BUILDTF = 
	CUTRG = 	#mandatory parameter
	TEMPLATE_NSIDE = 
	RSTEP = 	#mandatory parameter
	GAINSTEP = 	#mandatory parameter
	Nside = 	#mandatory parameter
	do_foscat = []
	number_of_do_foscat = 	#mandatory parameter
	do_templates = []
	number_of_do_templates = 	#mandatory parameter
	XI2STOP = 	#mandatory parameter
	AVGDUST = 	#mandatory parameter
	NITT = 	#mandatory parameter
	N_IN_ITT = 	#mandatory parameter
	NADU = []
	number_of_NADU = 	#mandatory parameter
	NADUSTEP = []
	number_of_NADUSTEP = 	#mandatory parameter
	in_template_map = []
	number_of_in_template_map = 
	number_val = 	#mandatory parameter
	beg_surv = []
	number_of_beg_surv = 	#mandatory parameter
	end_surv = []
	number_of_end_surv = 	#mandatory parameter
	name_surv = []
	number_of_name_surv = 	#mandatory parameter
	do_mean = []
	number_of_do_mean = 	#mandatory parameter
	val_mean = []
	number_of_val_mean = 	#mandatory parameter
	w_mean = []
	number_of_w_mean = 	#mandatory parameter
	UNSEEN = 	#mandatory parameter
	projection = 
	NORM_GAIN = 	#mandatory parameter
	REMOVE_CAL = 	#mandatory parameter
	Signal = []
	number_of_Signal = 
	External = []
	number_of_External = 
	rgcnn = []
	number_of_rgcnn = 
	invgi = []
	number_of_invgi = 
	Sub_HPR = []
	number_of_Sub_HPR = 
	SparseFunc = 
	DiagFunc = 
	External_MAP = []
	number_of_External_MAP = 
	Ptg = []
	number_of_Ptg = 
	Hit = []
	number_of_Hit = 
	HPR_Calib = []
	number_of_HPR_Calib = 
	Badring = []
	number_of_Badring = 
	VarGain = []
	number_of_VarGain = 
	Mask = 
	Out_MAP = []
	number_of_Out_MAP = 
	Out_VEC = []
	number_of_Out_VEC = 
	verbose = 
	dmc_output_path = 
	dmc_error_path = 
	stim_paramfiles = []
	number_of_stim_paramfiles = 
	MAPRINGS = []
	number_of_MAPRINGS = 
	ADDDIP = 
	addHPR_name = []
	number_of_addHPR_name = 
	addHPR_factor = []
	number_of_addHPR_factor = 
	addHPR_watts = []
	number_of_addHPR_watts = 
	delta_psi = []
	number_of_delta_psi = 
	MAP_CNN = 
	INST_CNN = 

	params  =vars()
	return params