
#define _XOPEN_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <assert.h>

#include "adu_to_volts.h"
#include "stim_tools.h"

#include "binary_file_toi.h"


// set to a mpi rank number to save the 3pt demodulated signal generated by this rank
#define DEBUG_RANK (-1)

// signal is converted to Volts in place,
// and a 3pt demodulated signal in Volts is stored in signal_3ptdemod if the pointer is not NULL,
// but is not used for now by stim

int adu_to_volts( stimParameters *stimPar, PIOFLOAT *signal, PIOFLOAT *signal_3ptdemod) {

  long i;
  long first_index = stimPar->signal_first_sample_number;
  long sig_length  = stimPar->total_signal_length;
  long last_index  = first_index + sig_length - 1;

  STIM_TRACE( 1, "converting ADU to Volts (x%g) for rings %d-%d", stimPar->brimo.DSN2V, stimPar->BeginRing, stimPar->EndRing);

  // convert signal to Volts
  for (i = 0; i < sig_length; i++) {
    signal[i] *= stimPar->brimo.DSN2V;
  }

  if (signal_3ptdemod != NULL) {
    // demodulate signal in Volts with a 3pt filter
    STIM_TRACE( 1, "demodulating V signal with 3pt filter for rings %d-%d", stimPar->BeginRing, stimPar->EndRing);
    for (i = 1; i < sig_length - 1; i++) {
      signal_3ptdemod[i] = 0.25 * PARITY_MOD( first_index + i - 1) * signal[i - 1]
                         + 0.50 * PARITY_MOD( first_index + i)     * signal[i]
                         + 0.25 * PARITY_MOD( first_index + i + 1) * signal[i + 1];
    }

    signal_3ptdemod[0] = 0.50 * PARITY_MOD( first_index)     * signal[0]
                       + 0.50 * PARITY_MOD( first_index + 1) * signal[1];
                       
    signal_3ptdemod[sig_length - 1] = 0.50 * PARITY_MOD( last_index - 1) * signal[sig_length - 2]
                                    + 0.50 * PARITY_MOD( last_index)     * signal[sig_length - 1];

    if (stimPar->mpi_rank == DEBUG_RANK) {
      STIM_TRACE( 0, "writing 3pt demodulated baseline from %ld to %ld", first_index, last_index);
      assert( BFT_writeObject( "/pscratch1/RD12_data/dmc/MISS03/DATA/sylvain2_TOI/143-1a_stimtest_3ptdemod", "float32", first_index, sig_length, signal_3ptdemod) >= 0);
    }
  }

  if (stimPar->mpi_rank == DEBUG_RANK) {
    STIM_TRACE( 0, "writing modulated volt signal from %ld to %ld", first_index, last_index);
    assert( BFT_writeObject( "/pscratch1/RD12_data/dmc/MISS03/DATA/sylvain2_TOI/143-1a_stimtest_adu2volt_signal", "float32", first_index, sig_length, signal) >= 0);
  }

  return( 0);
}
