#!/bin/bash
#PBS -q mpi_1
#PBS -l select=1:ncpus=28:mem=115g
#PBS -l walltime=04:00:00

cd /home1/datahome/tfoulqui/MySroll/extraball/SrollEx/
module purge
source srollex_setenv.sh
cd sroll

module load impi/5.1.3.258
export LD_LIBRARY_PATH=/home1/datahome/tfoulqui/.conda/envs/sroll_env/lib

mpirun -n 8 ./troll_14tf /home1/datahome/tfoulqui/MySroll/extraball/SrollEx/run_troll/test_sroll3_857_data.troll.par


