#!/bin/bash
#PBS -q mpi
#PBS -l select=1:ncpus=28:mem=115g
#PBS -l walltime=01:00:00
#PBS -N unit_test_sroll
#PBS -e unit_test_sroll_error.log
#PBS -o unit_test_sroll_output.log
#PBS -m n

cd /home1/datahome/tfoulqui/iaocea/source/SrollEx/
module purge
source srollex_setenv.sh
cd sroll

module load impi/5.1.3.258
export LD_LIBRARY_PATH=/home1/datahome/tfoulqui/.conda/envs/sroll_env/lib
#mpirun -np 8 ./troll_14tf /home1/datahome/tfoulqui/iaocea/source/SrollEx/run_troll/unit_test/unit_test_sroll3_857_data.troll.par
mpirun -np 8 ./troll_14tf /home1/datahome/tfoulqui/iaocea/source/SrollEx/run_troll/unit_test/sroll_unit_test_params.par
