#!/bin/bash
#PBS -q mpi
#PBS -l select=2:ncpus=28:mem=115g
#PBS -l walltime=10:00:00
#PBS -N runCFOSAT_sroll
#PBS -e error_runCFOSAT_sroll.log
#PBS -o out_runCFOSAT_sroll.log
#PBS -m n

cd /home1/datahome/tfoulqui/sroll-workspace/srollex/
module purge
source srollex_setenv.sh
cd sroll4
module load impi/5.1.3.258
echo 'python'
echo $PYTHONPATH

mpirun -np 8 ./troll_cfosat unit_test_cfosat.py &> /home1/datahome/tfoulqui/sroll-workspace/srollex/run_troll/run_cfosat/sunit_test_roll4_cfosat_data.log
