#!/bin/sh
#PBS -S /bin/sh
#PBS -N sroll_545_all
#PBS -j oe
#PBS -l nodes=11:ppn=24,walltime=5:00:00

cd /wrk/delouis/SROLL/Level2/Task_pkg/SrollEx/sroll


# Configure module
source ../srollex_setenv.sh

#mpirun --map-by node --display-map -x TMPDIR=/tmp -np 256 ./sroll /pscratch1/delouis/MONOBOL/545-1/param.txt &> /pscratch1/delouis/MONOBOL/545-1/DBG_sroll_proc.log
#mpirun --map-by node --display-map -x TMPDIR=/tmp -np 256 ./sroll /pscratch1/delouis/MONOBOL/545-2/param.txt &> /pscratch1/delouis/MONOBOL/545-2/DBG_sroll_proc.log
#mpirun --map-by node --display-map -x TMPDIR=/tmp -np 256 ./sroll /pscratch1/delouis/MONOBOL/545-4/param.txt &> /pscratch1/delouis/MONOBOL/545-4/DBG_sroll_proc.log
#
#mpirun --map-by node --display-map -x TMPDIR=/tmp -np 256 ./sroll /pscratch1/delouis/MONOBOL/545-1/paramkcmb.txt &> /pscratch1/delouis/MONOBOL/545-1/DBG_sroll_proc_kcmb.log
#mpirun --map-by node --display-map -x TMPDIR=/tmp -np 256 ./sroll /pscratch1/delouis/MONOBOL/545-2/paramkcmb.txt &> /pscratch1/delouis/MONOBOL/545-2/DBG_sroll_proc_kcmb.log
#mpirun --map-by node --display-map -x TMPDIR=/tmp -np 256 ./sroll /pscratch1/delouis/MONOBOL/545-4/paramkcmb.txt &> /pscratch1/delouis/MONOBOL/545-4/DBG_sroll_proc_kcmb.log

mpirun --map-by node --display-map -x TMPDIR=/tmp -np 256 ./sroll /wrk/delouis/SROLL/Level2/Task_pkg/SrollEx/sroll/Params/fitang/param545.txt &> /pscratch1/delouis/fitang/545/DBG_sroll_proc.log
mpirun --map-by node --display-map -x TMPDIR=/tmp -np 256 ./sroll /wrk/delouis/SROLL/Level2/Task_pkg/SrollEx/sroll/Params/fitang/param545_kcmb.txt &> /pscratch1/delouis/fitang/545/DBG_sroll_proc_kcmb.log

exit 0
